### PR TITLE
Make Pastel OCaml < 4.05 compatible

### PR DESCRIPTION
**Pull request by davesnx**
- Shadow bool_of_string_opt implementation

I would love to have the similar CI setup as facebook/reason to ensure we run against all OCaml versions.

### CODE REVIEW

**Review by bandersongit — APPROVED** [review]
Looks good to me, thanks for doing this!

**Comment by davesnx** [comment]
Hey @bandersongit, is there any reason why this can't be merged? Currently blocking a bit :S

**Comment by bandersongit** [comment]
I forget why this didn't work and I don't actually have the permissions to merge this anymore. Tagging @kyldvs

**Comment by davesnx** [comment]
I probably can yes, Thanks for the fast reply.

**Pull request merged**
